### ISSUE TITLE
How to rename the dmz-sd[x]

### ISSUE THREAD

**Issue by kenneth104** [hgst/dm-zoned-tools#11]
My first language is not English, please forgive me

Hello,my disk is conflict,Try to fix it to no avail

HostA,B
DiskAa Ab a lot of in HostA
DiskBa Bb a lot of in HostB

If move DiskAa to HostB , and start it
Will return an error , because the name is the same  "dmz-sda"

![1](https://user-images.githubusercontent.com/15079279/130315608-3e6f71f4-5196-4961-b5eb-a2ea84d63ab6.png)

**Comment by damien-lemoal** [comment]
I could recreate this problem. I have a fix now under test. I will release it tomorrow once testing completes.

**Comment by damien-lemoal** [comment]
I pushed some patches that should solve this problem. Please try.

With the latest changes, for your case (device was renamed from sdX to sdY), when doing "dmzadm --start", you will see a warning printed:

```
WARNING sdY: label dmz-sdX is already used, relabelling to dmz-sdY
```

To permanently remove this warning, you can use the new "--relabel" operation. This will change the device label to be "dmz-serial" where serial is the serial number of the device, so a unique label that will be usable regardless of the disk name.

```
dmzadm --relabel /dev/sdY
```

If you prefer labels that use the current device name, you can also do:

```
dmzadm --relabel /dev/sdY --label=dmz-sdY
```

Let me know if this works.

**Comment by kenneth104** [comment]
Thanks a lot
can be renamed normally

It's Work!!
