### ISSUE TITLE
sdc: Not a zoned block device

### ISSUE THREAD

**Issue by KyleSanderson** [hgst/dm-zoned-tools#3]
Model Family:     Seagate Archive HDD
Device Model:     ST8000AS0002-1NA17Z
User Capacity:    8,001,563,222,016 bytes [8.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5980 rpm
Device is:        In smartctl database [for details use: -P show]
ATA Version is:   ACS-2, ACS-3 T13/2161-D revision 3b
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Tue Dec 17 21:56:10 2019 PST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
AAM feature is:   Unavailable
APM feature is:   Unavailable
Rd look-ahead is: Enabled
Write cache is:   Enabled
DSN feature is:   Unavailable
ATA Security is:  Disabled, NOT FROZEN [SEC1]
Wt Cache Reorder: Unavailable

What gives? This is the definition of a SMR device.

**Comment by KyleSanderson** [comment]
Drive found in smartmontools Database.  Drive identity strings:
MODEL:              ST8000AS0002-1NA17Z
FIRMWARE:           AR15
match smartmontools Drive Database entry:
MODEL REGEXP:       ST[568]000AS00[01][12]-.*
FIRMWARE REGEXP:    .*
MODEL FAMILY:       Seagate Archive HDD
ATTRIBUTE OPTIONS:  None preset; no -v options are required.

**Comment by damien-lemoal** [comment]
Isn't this drive a drive-managed model ? By this I mean that the recording technology may be SMR, but the disk firmware does not support ZAC (zoned commands) and so the host only sees a regular block device. What does "cat /sys/block/<disk name>/queue/zoned" says ?
If you get "none" then the disk is not a zoned block device despite using SMR technology internally. Only "host-managed" and "host-aware" disk models expose the zone commands interface (ZAC for ATA and ZBC for SCSI).

**Comment by KyleSanderson** [comment]
Ah damn - that's a shame. Thanks for the heads up - I think you're right per https://lists.freebsd.org/pipermail/freebsd-current/2016-May/061448.html . I can't seem to find firmware for it online...

The performance characteristics are the same as a zoned disk which is why I was hopeful this would be a huge improvement. Oh well 😢 .

**Comment by damien-lemoal** [comment]
A lot of large-capacity consumer drives are like this, drive-managed and not host-managed or even host-aware, since that allows backward compatibility with regular disks.
Cheers!
